// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gisrvkaladhzmcvocdvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpc3J2a2FsYWRoem1jdm9jZHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDM5OTIsImV4cCI6MjA2MjU3OTk5Mn0._TsOMipiS0IUlc_F-Jj0ZHQtoxcwqp6D-YCPX_e5tVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);